# Generated by Django 5.2.14 on 2026-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
